// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: awsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNKNOWN        MessageType = 0
	MessageType_MESSAGE_TYPE_HANDSHAKE      MessageType = 1
	MessageType_MESSAGE_TYPE_HANDSHAKE_ACK  MessageType = 2
	MessageType_MESSAGE_TYPE_QUERY          MessageType = 3
	MessageType_MESSAGE_TYPE_QUERY_RESULT   MessageType = 4
	MessageType_MESSAGE_TYPE_SYNC_REQUEST   MessageType = 5
	MessageType_MESSAGE_TYPE_SYNC_RESPONSE  MessageType = 6
	MessageType_MESSAGE_TYPE_MIRROR_REQUEST MessageType = 7
	MessageType_MESSAGE_TYPE_MIRROR_DATA    MessageType = 8
	MessageType_MESSAGE_TYPE_MIRROR_ACK     MessageType = 9
	MessageType_MESSAGE_TYPE_PUSH_ENTRY     MessageType = 10
	MessageType_MESSAGE_TYPE_PUSH_ACK       MessageType = 11
	MessageType_MESSAGE_TYPE_RATING_PUSH    MessageType = 12
	MessageType_MESSAGE_TYPE_RATING_ACK     MessageType = 13
	MessageType_MESSAGE_TYPE_HEARTBEAT      MessageType = 14
	MessageType_MESSAGE_TYPE_BITFIELD       MessageType = 15
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNKNOWN",
		1:  "MESSAGE_TYPE_HANDSHAKE",
		2:  "MESSAGE_TYPE_HANDSHAKE_ACK",
		3:  "MESSAGE_TYPE_QUERY",
		4:  "MESSAGE_TYPE_QUERY_RESULT",
		5:  "MESSAGE_TYPE_SYNC_REQUEST",
		6:  "MESSAGE_TYPE_SYNC_RESPONSE",
		7:  "MESSAGE_TYPE_MIRROR_REQUEST",
		8:  "MESSAGE_TYPE_MIRROR_DATA",
		9:  "MESSAGE_TYPE_MIRROR_ACK",
		10: "MESSAGE_TYPE_PUSH_ENTRY",
		11: "MESSAGE_TYPE_PUSH_ACK",
		12: "MESSAGE_TYPE_RATING_PUSH",
		13: "MESSAGE_TYPE_RATING_ACK",
		14: "MESSAGE_TYPE_HEARTBEAT",
		15: "MESSAGE_TYPE_BITFIELD",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNKNOWN":        0,
		"MESSAGE_TYPE_HANDSHAKE":      1,
		"MESSAGE_TYPE_HANDSHAKE_ACK":  2,
		"MESSAGE_TYPE_QUERY":          3,
		"MESSAGE_TYPE_QUERY_RESULT":   4,
		"MESSAGE_TYPE_SYNC_REQUEST":   5,
		"MESSAGE_TYPE_SYNC_RESPONSE":  6,
		"MESSAGE_TYPE_MIRROR_REQUEST": 7,
		"MESSAGE_TYPE_MIRROR_DATA":    8,
		"MESSAGE_TYPE_MIRROR_ACK":     9,
		"MESSAGE_TYPE_PUSH_ENTRY":     10,
		"MESSAGE_TYPE_PUSH_ACK":       11,
		"MESSAGE_TYPE_RATING_PUSH":    12,
		"MESSAGE_TYPE_RATING_ACK":     13,
		"MESSAGE_TYPE_HEARTBEAT":      14,
		"MESSAGE_TYPE_BITFIELD":       15,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_awsp_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_awsp_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{0}
}

// 节点类型
type NodeType int32

const (
	NodeType_NODE_TYPE_LOCAL NodeType = 0
	NodeType_NODE_TYPE_SEED  NodeType = 1
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_LOCAL",
		1: "NODE_TYPE_SEED",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_LOCAL": 0,
		"NODE_TYPE_SEED":  1,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_awsp_proto_enumTypes[1].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_awsp_proto_enumTypes[1]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{1}
}

// 查询类型
type QueryType int32

const (
	QueryType_QUERY_TYPE_LOCAL  QueryType = 0
	QueryType_QUERY_TYPE_GLOBAL QueryType = 1
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_LOCAL",
		1: "QUERY_TYPE_GLOBAL",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_LOCAL":  0,
		"QUERY_TYPE_GLOBAL": 1,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_awsp_proto_enumTypes[2].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_awsp_proto_enumTypes[2]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{2}
}

// 消息头
type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=awsp.MessageType" json:"type,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_awsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *MessageHeader) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageHeader) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// 完整消息封装
type Message struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Handshake
	//	*Message_HandshakeAck
	//	*Message_Query
	//	*Message_QueryResult
	//	*Message_SyncRequest
	//	*Message_SyncResponse
	//	*Message_MirrorRequest
	//	*Message_MirrorData
	//	*Message_MirrorAck
	//	*Message_PushEntry
	//	*Message_PushAck
	//	*Message_RatingPush
	//	*Message_RatingAck
	//	*Message_Heartbeat
	//	*Message_Bitfield
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_awsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*Message_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Message) GetHandshakeAck() *HandshakeAck {
	if x != nil {
		if x, ok := x.Payload.(*Message_HandshakeAck); ok {
			return x.HandshakeAck
		}
	}
	return nil
}

func (x *Message) GetQuery() *Query {
	if x != nil {
		if x, ok := x.Payload.(*Message_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *Message) GetQueryResult() *QueryResult {
	if x != nil {
		if x, ok := x.Payload.(*Message_QueryResult); ok {
			return x.QueryResult
		}
	}
	return nil
}

func (x *Message) GetSyncRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *Message) GetSyncResponse() *SyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*Message_SyncResponse); ok {
			return x.SyncResponse
		}
	}
	return nil
}

func (x *Message) GetMirrorRequest() *MirrorRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_MirrorRequest); ok {
			return x.MirrorRequest
		}
	}
	return nil
}

func (x *Message) GetMirrorData() *MirrorData {
	if x != nil {
		if x, ok := x.Payload.(*Message_MirrorData); ok {
			return x.MirrorData
		}
	}
	return nil
}

func (x *Message) GetMirrorAck() *MirrorAck {
	if x != nil {
		if x, ok := x.Payload.(*Message_MirrorAck); ok {
			return x.MirrorAck
		}
	}
	return nil
}

func (x *Message) GetPushEntry() *PushEntry {
	if x != nil {
		if x, ok := x.Payload.(*Message_PushEntry); ok {
			return x.PushEntry
		}
	}
	return nil
}

func (x *Message) GetPushAck() *PushAck {
	if x != nil {
		if x, ok := x.Payload.(*Message_PushAck); ok {
			return x.PushAck
		}
	}
	return nil
}

func (x *Message) GetRatingPush() *RatingPush {
	if x != nil {
		if x, ok := x.Payload.(*Message_RatingPush); ok {
			return x.RatingPush
		}
	}
	return nil
}

func (x *Message) GetRatingAck() *RatingAck {
	if x != nil {
		if x, ok := x.Payload.(*Message_RatingAck); ok {
			return x.RatingAck
		}
	}
	return nil
}

func (x *Message) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Message_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Message) GetBitfield() *Bitfield {
	if x != nil {
		if x, ok := x.Payload.(*Message_Bitfield); ok {
			return x.Bitfield
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,2,opt,name=handshake,proto3,oneof"`
}

type Message_HandshakeAck struct {
	HandshakeAck *HandshakeAck `protobuf:"bytes,3,opt,name=handshake_ack,json=handshakeAck,proto3,oneof"`
}

type Message_Query struct {
	Query *Query `protobuf:"bytes,4,opt,name=query,proto3,oneof"`
}

type Message_QueryResult struct {
	QueryResult *QueryResult `protobuf:"bytes,5,opt,name=query_result,json=queryResult,proto3,oneof"`
}

type Message_SyncRequest struct {
	SyncRequest *SyncRequest `protobuf:"bytes,6,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

type Message_SyncResponse struct {
	SyncResponse *SyncResponse `protobuf:"bytes,7,opt,name=sync_response,json=syncResponse,proto3,oneof"`
}

type Message_MirrorRequest struct {
	MirrorRequest *MirrorRequest `protobuf:"bytes,8,opt,name=mirror_request,json=mirrorRequest,proto3,oneof"`
}

type Message_MirrorData struct {
	MirrorData *MirrorData `protobuf:"bytes,9,opt,name=mirror_data,json=mirrorData,proto3,oneof"`
}

type Message_MirrorAck struct {
	MirrorAck *MirrorAck `protobuf:"bytes,10,opt,name=mirror_ack,json=mirrorAck,proto3,oneof"`
}

type Message_PushEntry struct {
	PushEntry *PushEntry `protobuf:"bytes,11,opt,name=push_entry,json=pushEntry,proto3,oneof"`
}

type Message_PushAck struct {
	PushAck *PushAck `protobuf:"bytes,12,opt,name=push_ack,json=pushAck,proto3,oneof"`
}

type Message_RatingPush struct {
	RatingPush *RatingPush `protobuf:"bytes,13,opt,name=rating_push,json=ratingPush,proto3,oneof"`
}

type Message_RatingAck struct {
	RatingAck *RatingAck `protobuf:"bytes,14,opt,name=rating_ack,json=ratingAck,proto3,oneof"`
}

type Message_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,15,opt,name=heartbeat,proto3,oneof"`
}

type Message_Bitfield struct {
	Bitfield *Bitfield `protobuf:"bytes,16,opt,name=bitfield,proto3,oneof"`
}

func (*Message_Handshake) isMessage_Payload() {}

func (*Message_HandshakeAck) isMessage_Payload() {}

func (*Message_Query) isMessage_Payload() {}

func (*Message_QueryResult) isMessage_Payload() {}

func (*Message_SyncRequest) isMessage_Payload() {}

func (*Message_SyncResponse) isMessage_Payload() {}

func (*Message_MirrorRequest) isMessage_Payload() {}

func (*Message_MirrorData) isMessage_Payload() {}

func (*Message_MirrorAck) isMessage_Payload() {}

func (*Message_PushEntry) isMessage_Payload() {}

func (*Message_PushAck) isMessage_Payload() {}

func (*Message_RatingPush) isMessage_Payload() {}

func (*Message_RatingAck) isMessage_Payload() {}

func (*Message_Heartbeat) isMessage_Payload() {}

func (*Message_Bitfield) isMessage_Payload() {}

// 握手消息
type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	NodeType      NodeType               `protobuf:"varint,3,opt,name=node_type,json=nodeType,proto3,enum=awsp.NodeType" json:"node_type,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Categories    []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	EntryCount    int64                  `protobuf:"varint,6,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_awsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{2}
}

func (x *Handshake) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Handshake) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Handshake) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_LOCAL
}

func (x *Handshake) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Handshake) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Handshake) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *Handshake) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HandshakeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	NodeType      NodeType               `protobuf:"varint,3,opt,name=node_type,json=nodeType,proto3,enum=awsp.NodeType" json:"node_type,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Accepted      bool                   `protobuf:"varint,5,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,6,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeAck) Reset() {
	*x = HandshakeAck{}
	mi := &file_awsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeAck) ProtoMessage() {}

func (x *HandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeAck.ProtoReflect.Descriptor instead.
func (*HandshakeAck) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HandshakeAck) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *HandshakeAck) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_LOCAL
}

func (x *HandshakeAck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *HandshakeAck) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// 查询消息
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Categories    []string               `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	QueryType     QueryType              `protobuf:"varint,6,opt,name=query_type,json=queryType,proto3,enum=awsp.QueryType" json:"query_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_awsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{4}
}

func (x *Query) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *Query) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *Query) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Query) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Query) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Query) GetQueryType() QueryType {
	if x != nil {
		return x.QueryType
	}
	return QueryType_QUERY_TYPE_LOCAL
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Entries       [][]byte               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_awsp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResult) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResult) GetEntries() [][]byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryResult) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QueryResult) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 同步消息
type SyncRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LastSyncTimestamp   int64                  `protobuf:"varint,2,opt,name=last_sync_timestamp,json=lastSyncTimestamp,proto3" json:"last_sync_timestamp,omitempty"`
	VersionVector       map[string]int64       `protobuf:"bytes,3,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RequestedCategories []string               `protobuf:"bytes,4,rep,name=requested_categories,json=requestedCategories,proto3" json:"requested_categories,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_awsp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{6}
}

func (x *SyncRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncRequest) GetLastSyncTimestamp() int64 {
	if x != nil {
		return x.LastSyncTimestamp
	}
	return 0
}

func (x *SyncRequest) GetVersionVector() map[string]int64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *SyncRequest) GetRequestedCategories() []string {
	if x != nil {
		return x.RequestedCategories
	}
	return nil
}

type SyncResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NewEntries          [][]byte               `protobuf:"bytes,2,rep,name=new_entries,json=newEntries,proto3" json:"new_entries,omitempty"`
	UpdatedEntries      [][]byte               `protobuf:"bytes,3,rep,name=updated_entries,json=updatedEntries,proto3" json:"updated_entries,omitempty"`
	DeletedEntryIds     []string               `protobuf:"bytes,4,rep,name=deleted_entry_ids,json=deletedEntryIds,proto3" json:"deleted_entry_ids,omitempty"`
	NewRatings          [][]byte               `protobuf:"bytes,5,rep,name=new_ratings,json=newRatings,proto3" json:"new_ratings,omitempty"`
	ServerVersionVector map[string]int64       `protobuf:"bytes,6,rep,name=server_version_vector,json=serverVersionVector,proto3" json:"server_version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ServerTimestamp     int64                  `protobuf:"varint,7,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_awsp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{7}
}

func (x *SyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncResponse) GetNewEntries() [][]byte {
	if x != nil {
		return x.NewEntries
	}
	return nil
}

func (x *SyncResponse) GetUpdatedEntries() [][]byte {
	if x != nil {
		return x.UpdatedEntries
	}
	return nil
}

func (x *SyncResponse) GetDeletedEntryIds() []string {
	if x != nil {
		return x.DeletedEntryIds
	}
	return nil
}

func (x *SyncResponse) GetNewRatings() [][]byte {
	if x != nil {
		return x.NewRatings
	}
	return nil
}

func (x *SyncResponse) GetServerVersionVector() map[string]int64 {
	if x != nil {
		return x.ServerVersionVector
	}
	return nil
}

func (x *SyncResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// 镜像消息
type MirrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Categories    []string               `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	FullMirror    bool                   `protobuf:"varint,3,opt,name=full_mirror,json=fullMirror,proto3" json:"full_mirror,omitempty"`
	BatchSize     int32                  `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorRequest) Reset() {
	*x = MirrorRequest{}
	mi := &file_awsp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorRequest) ProtoMessage() {}

func (x *MirrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorRequest.ProtoReflect.Descriptor instead.
func (*MirrorRequest) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{8}
}

func (x *MirrorRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MirrorRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *MirrorRequest) GetFullMirror() bool {
	if x != nil {
		return x.FullMirror
	}
	return false
}

func (x *MirrorRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type MirrorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	BatchIndex    int32                  `protobuf:"varint,2,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	TotalBatches  int32                  `protobuf:"varint,3,opt,name=total_batches,json=totalBatches,proto3" json:"total_batches,omitempty"`
	Entries       [][]byte               `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	Categories    [][]byte               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorData) Reset() {
	*x = MirrorData{}
	mi := &file_awsp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorData) ProtoMessage() {}

func (x *MirrorData) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorData.ProtoReflect.Descriptor instead.
func (*MirrorData) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{9}
}

func (x *MirrorData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MirrorData) GetBatchIndex() int32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *MirrorData) GetTotalBatches() int32 {
	if x != nil {
		return x.TotalBatches
	}
	return 0
}

func (x *MirrorData) GetEntries() [][]byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *MirrorData) GetCategories() [][]byte {
	if x != nil {
		return x.Categories
	}
	return nil
}

type MirrorAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ReceivedEntries int64                  `protobuf:"varint,4,opt,name=received_entries,json=receivedEntries,proto3" json:"received_entries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MirrorAck) Reset() {
	*x = MirrorAck{}
	mi := &file_awsp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorAck) ProtoMessage() {}

func (x *MirrorAck) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorAck.ProtoReflect.Descriptor instead.
func (*MirrorAck) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{10}
}

func (x *MirrorAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MirrorAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MirrorAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MirrorAck) GetReceivedEntries() int64 {
	if x != nil {
		return x.ReceivedEntries
	}
	return 0
}

// 推送消息
type PushEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntryId          string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Entry            []byte                 `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	CreatorSignature []byte                 `protobuf:"bytes,3,opt,name=creator_signature,json=creatorSignature,proto3" json:"creator_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushEntry) Reset() {
	*x = PushEntry{}
	mi := &file_awsp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEntry) ProtoMessage() {}

func (x *PushEntry) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEntry.ProtoReflect.Descriptor instead.
func (*PushEntry) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{11}
}

func (x *PushEntry) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *PushEntry) GetEntry() []byte {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *PushEntry) GetCreatorSignature() []byte {
	if x != nil {
		return x.CreatorSignature
	}
	return nil
}

type PushAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	NewVersion    int64                  `protobuf:"varint,4,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_awsp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{12}
}

func (x *PushAck) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *PushAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PushAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *PushAck) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type RatingPush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rating         []byte                 `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	RaterSignature []byte                 `protobuf:"bytes,2,opt,name=rater_signature,json=raterSignature,proto3" json:"rater_signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RatingPush) Reset() {
	*x = RatingPush{}
	mi := &file_awsp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingPush) ProtoMessage() {}

func (x *RatingPush) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingPush.ProtoReflect.Descriptor instead.
func (*RatingPush) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{13}
}

func (x *RatingPush) GetRating() []byte {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *RatingPush) GetRaterSignature() []byte {
	if x != nil {
		return x.RaterSignature
	}
	return nil
}

type RatingAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatingId      string                 `protobuf:"bytes,1,opt,name=rating_id,json=ratingId,proto3" json:"rating_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingAck) Reset() {
	*x = RatingAck{}
	mi := &file_awsp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingAck) ProtoMessage() {}

func (x *RatingAck) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingAck.ProtoReflect.Descriptor instead.
func (*RatingAck) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{14}
}

func (x *RatingAck) GetRatingId() string {
	if x != nil {
		return x.RatingId
	}
	return ""
}

func (x *RatingAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RatingAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// 心跳与状态消息
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	EntryCount    int64                  `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_awsp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{15}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Bitfield struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VersionVector map[string]int64       `protobuf:"bytes,2,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	EntryCount    int64                  `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bitfield) Reset() {
	*x = Bitfield{}
	mi := &file_awsp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bitfield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bitfield) ProtoMessage() {}

func (x *Bitfield) ProtoReflect() protoreflect.Message {
	mi := &file_awsp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bitfield.ProtoReflect.Descriptor instead.
func (*Bitfield) Descriptor() ([]byte, []int) {
	return file_awsp_proto_rawDescGZIP(), []int{16}
}

func (x *Bitfield) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Bitfield) GetVersionVector() map[string]int64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *Bitfield) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

var File_awsp_proto protoreflect.FileDescriptor

const file_awsp_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"awsp.proto\x12\x04awsp\"\x91\x01\n" +
	"\rMessageHeader\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.awsp.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xc6\x06\n" +
	"\aMessage\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.awsp.MessageHeaderR\x06header\x12/\n" +
	"\thandshake\x18\x02 \x01(\v2\x0f.awsp.HandshakeH\x00R\thandshake\x129\n" +
	"\rhandshake_ack\x18\x03 \x01(\v2\x12.awsp.HandshakeAckH\x00R\fhandshakeAck\x12#\n" +
	"\x05query\x18\x04 \x01(\v2\v.awsp.QueryH\x00R\x05query\x126\n" +
	"\fquery_result\x18\x05 \x01(\v2\x11.awsp.QueryResultH\x00R\vqueryResult\x126\n" +
	"\fsync_request\x18\x06 \x01(\v2\x11.awsp.SyncRequestH\x00R\vsyncRequest\x129\n" +
	"\rsync_response\x18\a \x01(\v2\x12.awsp.SyncResponseH\x00R\fsyncResponse\x12<\n" +
	"\x0emirror_request\x18\b \x01(\v2\x13.awsp.MirrorRequestH\x00R\rmirrorRequest\x123\n" +
	"\vmirror_data\x18\t \x01(\v2\x10.awsp.MirrorDataH\x00R\n" +
	"mirrorData\x120\n" +
	"\n" +
	"mirror_ack\x18\n" +
	" \x01(\v2\x0f.awsp.MirrorAckH\x00R\tmirrorAck\x120\n" +
	"\n" +
	"push_entry\x18\v \x01(\v2\x0f.awsp.PushEntryH\x00R\tpushEntry\x12*\n" +
	"\bpush_ack\x18\f \x01(\v2\r.awsp.PushAckH\x00R\apushAck\x123\n" +
	"\vrating_push\x18\r \x01(\v2\x10.awsp.RatingPushH\x00R\n" +
	"ratingPush\x120\n" +
	"\n" +
	"rating_ack\x18\x0e \x01(\v2\x0f.awsp.RatingAckH\x00R\tratingAck\x12/\n" +
	"\theartbeat\x18\x0f \x01(\v2\x0f.awsp.HeartbeatH\x00R\theartbeat\x12,\n" +
	"\bbitfield\x18\x10 \x01(\v2\x0e.awsp.BitfieldH\x00R\bbitfieldB\t\n" +
	"\apayload\"\xe3\x01\n" +
	"\tHandshake\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12+\n" +
	"\tnode_type\x18\x03 \x01(\x0e2\x0e.awsp.NodeTypeR\bnodeType\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\tR\n" +
	"categories\x12\x1f\n" +
	"\ventry_count\x18\x06 \x01(\x03R\n" +
	"entryCount\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\xe6\x01\n" +
	"\fHandshakeAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12+\n" +
	"\tnode_type\x18\x03 \x01(\x0e2\x0e.awsp.NodeTypeR\bnodeType\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\baccepted\x18\x05 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x06 \x01(\tR\frejectReason\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\xba\x01\n" +
	"\x05Query\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12.\n" +
	"\n" +
	"query_type\x18\x06 \x01(\x0e2\x0f.awsp.QueryTypeR\tqueryType\"~\n" +
	"\vQueryResult\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x18\n" +
	"\aentries\x18\x02 \x03(\fR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x9e\x02\n" +
	"\vSyncRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12.\n" +
	"\x13last_sync_timestamp\x18\x02 \x01(\x03R\x11lastSyncTimestamp\x12K\n" +
	"\x0eversion_vector\x18\x03 \x03(\v2$.awsp.SyncRequest.VersionVectorEntryR\rversionVector\x121\n" +
	"\x14requested_categories\x18\x04 \x03(\tR\x13requestedCategories\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x98\x03\n" +
	"\fSyncResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vnew_entries\x18\x02 \x03(\fR\n" +
	"newEntries\x12'\n" +
	"\x0fupdated_entries\x18\x03 \x03(\fR\x0eupdatedEntries\x12*\n" +
	"\x11deleted_entry_ids\x18\x04 \x03(\tR\x0fdeletedEntryIds\x12\x1f\n" +
	"\vnew_ratings\x18\x05 \x03(\fR\n" +
	"newRatings\x12_\n" +
	"\x15server_version_vector\x18\x06 \x03(\v2+.awsp.SyncResponse.ServerVersionVectorEntryR\x13serverVersionVector\x12)\n" +
	"\x10server_timestamp\x18\a \x01(\x03R\x0fserverTimestamp\x1aF\n" +
	"\x18ServerVersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x8e\x01\n" +
	"\rMirrorRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1e\n" +
	"\n" +
	"categories\x18\x02 \x03(\tR\n" +
	"categories\x12\x1f\n" +
	"\vfull_mirror\x18\x03 \x01(\bR\n" +
	"fullMirror\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\"\xab\x01\n" +
	"\n" +
	"MirrorData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vbatch_index\x18\x02 \x01(\x05R\n" +
	"batchIndex\x12#\n" +
	"\rtotal_batches\x18\x03 \x01(\x05R\ftotalBatches\x12\x18\n" +
	"\aentries\x18\x04 \x03(\fR\aentries\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\fR\n" +
	"categories\"\x94\x01\n" +
	"\tMirrorAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10received_entries\x18\x04 \x01(\x03R\x0freceivedEntries\"i\n" +
	"\tPushEntry\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x14\n" +
	"\x05entry\x18\x02 \x01(\fR\x05entry\x12+\n" +
	"\x11creator_signature\x18\x03 \x01(\fR\x10creatorSignature\"\x86\x01\n" +
	"\aPushAck\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\x12\x1f\n" +
	"\vnew_version\x18\x04 \x01(\x03R\n" +
	"newVersion\"M\n" +
	"\n" +
	"RatingPush\x12\x16\n" +
	"\x06rating\x18\x01 \x01(\fR\x06rating\x12'\n" +
	"\x0frater_signature\x18\x02 \x01(\fR\x0eraterSignature\"i\n" +
	"\tRatingAck\x12\x1b\n" +
	"\trating_id\x18\x01 \x01(\tR\bratingId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\"\x8a\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x03R\n" +
	"entryCount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xd0\x01\n" +
	"\bBitfield\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12H\n" +
	"\x0eversion_vector\x18\x02 \x03(\v2!.awsp.Bitfield.VersionVectorEntryR\rversionVector\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x03R\n" +
	"entryCount\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01*\xdf\x03\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MESSAGE_TYPE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HANDSHAKE\x10\x01\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_HANDSHAKE_ACK\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_QUERY\x10\x03\x12\x1d\n" +
	"\x19MESSAGE_TYPE_QUERY_RESULT\x10\x04\x12\x1d\n" +
	"\x19MESSAGE_TYPE_SYNC_REQUEST\x10\x05\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_SYNC_RESPONSE\x10\x06\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_MIRROR_REQUEST\x10\a\x12\x1c\n" +
	"\x18MESSAGE_TYPE_MIRROR_DATA\x10\b\x12\x1b\n" +
	"\x17MESSAGE_TYPE_MIRROR_ACK\x10\t\x12\x1b\n" +
	"\x17MESSAGE_TYPE_PUSH_ENTRY\x10\n" +
	"\x12\x19\n" +
	"\x15MESSAGE_TYPE_PUSH_ACK\x10\v\x12\x1c\n" +
	"\x18MESSAGE_TYPE_RATING_PUSH\x10\f\x12\x1b\n" +
	"\x17MESSAGE_TYPE_RATING_ACK\x10\r\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\x0e\x12\x19\n" +
	"\x15MESSAGE_TYPE_BITFIELD\x10\x0f*3\n" +
	"\bNodeType\x12\x13\n" +
	"\x0fNODE_TYPE_LOCAL\x10\x00\x12\x12\n" +
	"\x0eNODE_TYPE_SEED\x10\x01*8\n" +
	"\tQueryType\x12\x14\n" +
	"\x10QUERY_TYPE_LOCAL\x10\x00\x12\x15\n" +
	"\x11QUERY_TYPE_GLOBAL\x10\x01B?Z=github.com/daifei0527/polyant/internal/network/protocol/protob\x06proto3"

var (
	file_awsp_proto_rawDescOnce sync.Once
	file_awsp_proto_rawDescData []byte
)

func file_awsp_proto_rawDescGZIP() []byte {
	file_awsp_proto_rawDescOnce.Do(func() {
		file_awsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_awsp_proto_rawDesc), len(file_awsp_proto_rawDesc)))
	})
	return file_awsp_proto_rawDescData
}

var file_awsp_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_awsp_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_awsp_proto_goTypes = []any{
	(MessageType)(0),      // 0: awsp.MessageType
	(NodeType)(0),         // 1: awsp.NodeType
	(QueryType)(0),        // 2: awsp.QueryType
	(*MessageHeader)(nil), // 3: awsp.MessageHeader
	(*Message)(nil),       // 4: awsp.Message
	(*Handshake)(nil),     // 5: awsp.Handshake
	(*HandshakeAck)(nil),  // 6: awsp.HandshakeAck
	(*Query)(nil),         // 7: awsp.Query
	(*QueryResult)(nil),   // 8: awsp.QueryResult
	(*SyncRequest)(nil),   // 9: awsp.SyncRequest
	(*SyncResponse)(nil),  // 10: awsp.SyncResponse
	(*MirrorRequest)(nil), // 11: awsp.MirrorRequest
	(*MirrorData)(nil),    // 12: awsp.MirrorData
	(*MirrorAck)(nil),     // 13: awsp.MirrorAck
	(*PushEntry)(nil),     // 14: awsp.PushEntry
	(*PushAck)(nil),       // 15: awsp.PushAck
	(*RatingPush)(nil),    // 16: awsp.RatingPush
	(*RatingAck)(nil),     // 17: awsp.RatingAck
	(*Heartbeat)(nil),     // 18: awsp.Heartbeat
	(*Bitfield)(nil),      // 19: awsp.Bitfield
	nil,                   // 20: awsp.SyncRequest.VersionVectorEntry
	nil,                   // 21: awsp.SyncResponse.ServerVersionVectorEntry
	nil,                   // 22: awsp.Bitfield.VersionVectorEntry
}
var file_awsp_proto_depIdxs = []int32{
	0,  // 0: awsp.MessageHeader.type:type_name -> awsp.MessageType
	3,  // 1: awsp.Message.header:type_name -> awsp.MessageHeader
	5,  // 2: awsp.Message.handshake:type_name -> awsp.Handshake
	6,  // 3: awsp.Message.handshake_ack:type_name -> awsp.HandshakeAck
	7,  // 4: awsp.Message.query:type_name -> awsp.Query
	8,  // 5: awsp.Message.query_result:type_name -> awsp.QueryResult
	9,  // 6: awsp.Message.sync_request:type_name -> awsp.SyncRequest
	10, // 7: awsp.Message.sync_response:type_name -> awsp.SyncResponse
	11, // 8: awsp.Message.mirror_request:type_name -> awsp.MirrorRequest
	12, // 9: awsp.Message.mirror_data:type_name -> awsp.MirrorData
	13, // 10: awsp.Message.mirror_ack:type_name -> awsp.MirrorAck
	14, // 11: awsp.Message.push_entry:type_name -> awsp.PushEntry
	15, // 12: awsp.Message.push_ack:type_name -> awsp.PushAck
	16, // 13: awsp.Message.rating_push:type_name -> awsp.RatingPush
	17, // 14: awsp.Message.rating_ack:type_name -> awsp.RatingAck
	18, // 15: awsp.Message.heartbeat:type_name -> awsp.Heartbeat
	19, // 16: awsp.Message.bitfield:type_name -> awsp.Bitfield
	1,  // 17: awsp.Handshake.node_type:type_name -> awsp.NodeType
	1,  // 18: awsp.HandshakeAck.node_type:type_name -> awsp.NodeType
	2,  // 19: awsp.Query.query_type:type_name -> awsp.QueryType
	20, // 20: awsp.SyncRequest.version_vector:type_name -> awsp.SyncRequest.VersionVectorEntry
	21, // 21: awsp.SyncResponse.server_version_vector:type_name -> awsp.SyncResponse.ServerVersionVectorEntry
	22, // 22: awsp.Bitfield.version_vector:type_name -> awsp.Bitfield.VersionVectorEntry
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_awsp_proto_init() }
func file_awsp_proto_init() {
	if File_awsp_proto != nil {
		return
	}
	file_awsp_proto_msgTypes[1].OneofWrappers = []any{
		(*Message_Handshake)(nil),
		(*Message_HandshakeAck)(nil),
		(*Message_Query)(nil),
		(*Message_QueryResult)(nil),
		(*Message_SyncRequest)(nil),
		(*Message_SyncResponse)(nil),
		(*Message_MirrorRequest)(nil),
		(*Message_MirrorData)(nil),
		(*Message_MirrorAck)(nil),
		(*Message_PushEntry)(nil),
		(*Message_PushAck)(nil),
		(*Message_RatingPush)(nil),
		(*Message_RatingAck)(nil),
		(*Message_Heartbeat)(nil),
		(*Message_Bitfield)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_awsp_proto_rawDesc), len(file_awsp_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_awsp_proto_goTypes,
		DependencyIndexes: file_awsp_proto_depIdxs,
		EnumInfos:         file_awsp_proto_enumTypes,
		MessageInfos:      file_awsp_proto_msgTypes,
	}.Build()
	File_awsp_proto = out.File
	file_awsp_proto_goTypes = nil
	file_awsp_proto_depIdxs = nil
}
